from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QScrollArea
import pandas as pd
from New_classes import Graph,Spectrogram
import numpy as np
from scipy.fft import fftshift
from scipy import signal
import matplotlib.pyplot as plt
from scipy.io import loadmat
#from pdf import PDF
import os
from pyqtgraph import PlotWidget, plot
import pyqtgraph as pg
#import pyqtgraph.exporters
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1119, 703)
        MainWindow.setWindowIcon(QtGui.QIcon("MainIcon.png"))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter_5 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.widget = QtWidgets.QWidget(self.splitter_2)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.multiChanel_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.multiChanel_label.setFont(font)
        self.multiChanel_label.setAutoFillBackground(True)
        self.multiChanel_label.setObjectName("multiChanel_label")
        self.horizontalLayout_4.addWidget(self.multiChanel_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.channel_title_label = QtWidgets.QLabel(self.widget)
        self.channel_title_label.setAutoFillBackground(True)
        self.channel_title_label.setObjectName("channel_title_label")
        self.horizontalLayout_2.addWidget(self.channel_title_label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.OK_Button = QtWidgets.QPushButton(self.widget)
        self.OK_Button.setObjectName("OK_Button")
        self.horizontalLayout_2.addWidget(self.OK_Button)
        self.OK_Button.setIcon(QtGui.QIcon(QtGui.QPixmap("setlabel.png")))

        spacerItem3 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.open_Button = QtWidgets.QPushButton(self.widget)
        self.open_Button.setObjectName("open_Button")
        self.horizontalLayout_2.addWidget(self.open_Button)
        self.open_Button.setIcon(QtGui.QIcon(QtGui.QPixmap("openicon.png")))

        self.chan_color_comboBox = QtWidgets.QComboBox(self.widget)
        self.chan_color_comboBox.setMouseTracking(False)
        self.chan_color_comboBox.setEditable(False)
        self.chan_color_comboBox.setCurrentText("red")
        self.chan_color_comboBox.setObjectName("chan_color_comboBox")
        self.chan_color_comboBox.addItem("")
        self.chan_color_comboBox.addItem("")
        self.chan_color_comboBox.addItem("")
        self.chan_color_comboBox.addItem("")
        self.chan_color_comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.chan_color_comboBox)
        self.select_sig_comboBox = QtWidgets.QComboBox(self.widget)
        self.select_sig_comboBox.setObjectName("select_sig_comboBox")
        self.select_sig_comboBox.addItem("Showed Signal")
        self.select_sig_comboBox.addItem("")
        self.select_sig_comboBox.addItem("")

        self.horizontalLayout_2.addWidget(self.select_sig_comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.chanels_verticalScrollBar = QtWidgets.QScrollBar(self.widget1)
        self.chanels_verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.chanels_verticalScrollBar.setObjectName("chanels_verticalScrollBar")
        self.chanels_verticalScrollBar.setValue(50)

        self.gridLayout.addWidget(self.chanels_verticalScrollBar, 0, 0, 1, 1)
        Graph.createPlotWidget()
        self.channels_graphicsView = Graph.getLastChannel()
        self.channels_graphicsView.setEnabled(True)
        #self.channels_graphicsView.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        #self.channels_graphicsView.setRenderHint(QtWidgets.QStylePainter.Antialiasing, True)
        self.gridLayout.addWidget(self.channels_graphicsView, 0, 1, 1, 1)
        self.chanels_horizontalScrollBar = QtWidgets.QScrollBar(self.widget1)
        self.chanels_horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.chanels_horizontalScrollBar.setObjectName("chanels_horizontalScrollBar")
        self.gridLayout.addWidget(self.chanels_horizontalScrollBar, 1, 1, 1, 1)
        self.widget2 = QtWidgets.QWidget(self.splitter)
        self.widget2.setObjectName("widget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.stop_play_Button = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_play_Button.sizePolicy().hasHeightForWidth())
        self.stop_play_Button.setSizePolicy(sizePolicy)
        self.stop_play_Button.setObjectName("chanels_stop_Button")
        self.verticalLayout.addWidget(self.stop_play_Button)
        self.stop_play_Button.setIcon(QtGui.QIcon(QtGui.QPixmap("pause.png")))
        self.chanel_zoomIn_Button = QtWidgets.QPushButton(self.widget2)
        self.chanel_zoomIn_Button.setIcon(QtGui.QIcon(QtGui.QPixmap("zoom-in.png")))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chanel_zoomIn_Button.sizePolicy().hasHeightForWidth())
        self.chanel_zoomIn_Button.setSizePolicy(sizePolicy)
        self.chanel_zoomIn_Button.setObjectName("chanels_zoomIn_Button")
        self.verticalLayout.addWidget(self.chanel_zoomIn_Button)
        self.chanels_zoomOut_Button = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chanels_zoomOut_Button.sizePolicy().hasHeightForWidth())
        self.chanels_zoomOut_Button.setSizePolicy(sizePolicy)
        self.chanels_zoomOut_Button.setObjectName("chanels_zoomOut_Button")
        self.chanels_zoomOut_Button.setIcon(QtGui.QIcon(QtGui.QPixmap("zoom-out.png")))

        self.verticalLayout.addWidget(self.chanels_zoomOut_Button)
        self.chanels_resetView_Button = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chanels_resetView_Button.sizePolicy().hasHeightForWidth())
        self.chanels_resetView_Button.setSizePolicy(sizePolicy)
        self.chanels_resetView_Button.setObjectName("chanels_resetView_Button")
        self.chanels_resetView_Button.setIcon(QtGui.QIcon(QtGui.QPixmap("resetview.jpeg")))

        self.verticalLayout.addWidget(self.chanels_resetView_Button)
        self.chanels_clear_Button = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chanels_clear_Button.sizePolicy().hasHeightForWidth())
        self.chanels_clear_Button.setSizePolicy(sizePolicy)
        self.chanels_clear_Button.setObjectName("chanels_clear_Button")
        self.verticalLayout.addWidget(self.chanels_clear_Button)
        self.chanels_clear_Button.setIcon(QtGui.QIcon(QtGui.QPixmap("delete.png")))

        self.show_hide_Button = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_hide_Button.sizePolicy().hasHeightForWidth())
        self.show_hide_Button.setSizePolicy(sizePolicy)
        self.show_hide_Button.setObjectName("chanels_hide_Button")
        self.verticalLayout.addWidget(self.show_hide_Button)
        self.show_hide_Button.setIcon(QtGui.QIcon(QtGui.QPixmap("hideicon.jpg")))

        self.horizontalLayout.addLayout(self.verticalLayout)
        self.chan_speed_verticalSlider = QtWidgets.QSlider(self.widget2)
        self.chan_speed_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.chan_speed_verticalSlider.setMinimum(1)
        self.chan_speed_verticalSlider.setMaximum(10)
        self.chan_speed_verticalSlider.setObjectName("chan_1_speed_verticalSlider")
        self.horizontalLayout.addWidget(self.chan_speed_verticalSlider)
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.widget3 = QtWidgets.QWidget(self.splitter_4)
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.spectrogram_label = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spectrogram_label.setFont(font)
        self.spectrogram_label.setAutoFillBackground(True)
        self.spectrogram_label.setObjectName("spectrogram_label")
        self.horizontalLayout_6.addWidget(self.spectrogram_label)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")

        Spectrogram.createSpectrogramWindow()
        self.spectrogram_graphicsView = Spectrogram.getSpectrogramWindow()
        self.splitter_3.addWidget(self.spectrogram_graphicsView)
        self.widget4 = QtWidgets.QWidget(self.splitter_3)
        self.widget4.setObjectName("widget4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.spectro_color_comboBox = QtWidgets.QComboBox(self.widget4)
        self.spectro_color_comboBox.setMouseTracking(False)
        self.spectro_color_comboBox.setEditable(False)
        self.spectro_color_comboBox.setObjectName("spectro_color_comboBox")
        self.spectro_color_comboBox.addItem("")
        self.spectro_color_comboBox.addItem("")
        self.spectro_color_comboBox.addItem("")
        self.spectro_color_comboBox.addItem("")
        self.spectro_color_comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.spectro_color_comboBox)
        self.specto_show_comboBox = QtWidgets.QComboBox(self.widget4)
        self.specto_show_comboBox.setEditable(False)
        self.specto_show_comboBox.addItem("")
        self.specto_show_comboBox.addItem("")
        self.specto_show_comboBox.addItem("")
        self.specto_show_comboBox.setObjectName("specto_show_comboBox")
        self.verticalLayout_3.addWidget(self.specto_show_comboBox)
        self.specto_clear_Button = QtWidgets.QPushButton(self.widget4)
        self.specto_clear_Button.setObjectName("specto_clear_Button")
        self.verticalLayout_3.addWidget(self.specto_clear_Button)
        self.specto_clear_Button.setIcon(QtGui.QIcon(QtGui.QPixmap("delete.png")))
        self.verticalLayout_4.addWidget(self.splitter_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1119, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionExport_as_PDF = QtWidgets.QAction(MainWindow)
        self.actionExport_as_PDF.setObjectName("actionExport_as_PDF")
        self.menufile.addAction(self.actionExport_as_PDF)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menufile.addAction(self.actionExit)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Multi-Signal Viewer"))
        self.multiChanel_label.setText(_translate("MainWindow", "Multi-Signal Viewer"))
        self.channel_title_label.setText(_translate("MainWindow", "Channel Title"))
        self.OK_Button.setText(_translate("MainWindow", "OK"))
        self.open_Button.setText(_translate("MainWindow", "Open"))
        self.chan_color_comboBox.setItemText(0, _translate("MainWindow", "red"))
        self.chan_color_comboBox.setItemText(1, _translate("MainWindow", "green"))
        self.chan_color_comboBox.setItemText(2, _translate("MainWindow", "yellow"))
        self.chan_color_comboBox.setItemText(3, _translate("MainWindow", "blue"))
        self.chan_color_comboBox.setItemText(4, _translate("MainWindow", "white"))
        self.stop_play_Button.setText(_translate("MainWindow", "stop"))
        self.chanel_zoomIn_Button.setText(_translate("MainWindow", "zoom in"))
        self.chanels_zoomOut_Button.setText(_translate("MainWindow", "zoom out"))
        self.chanels_resetView_Button.setText(_translate("MainWindow", "Reset View"))
        self.chanels_clear_Button.setText(_translate("MainWindow", "clear"))
        self.show_hide_Button.setText(_translate("MainWindow", "Hide"))
        self.spectrogram_label.setText(_translate("MainWindow", "Spectrogram"))
        self.spectro_color_comboBox.setCurrentText(_translate("MainWindow", "red"))
        self.spectro_color_comboBox.setItemText(0, _translate("MainWindow", "red"))
        self.spectro_color_comboBox.setItemText(1, _translate("MainWindow", "green"))
        self.spectro_color_comboBox.setItemText(2, _translate("MainWindow", "yellow"))
        self.spectro_color_comboBox.setItemText(3, _translate("MainWindow", "blue"))
        self.spectro_color_comboBox.setItemText(4, _translate("MainWindow", "white"))
        self.specto_show_comboBox.setCurrentText(_translate("MainWindow", "Show "))
        self.specto_clear_Button.setText(_translate("MainWindow", "Clear"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionExport_as_PDF.setText(_translate("MainWindow", "Export as PDF"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())